/* Search Converts shared behavior: lead forms + readability guard. <script src="/sc-site.js" defer> */
(function(){'use strict';
  var _L=[112,117,109,118,71,108,128,108,123,118,104,107,53,106,118,116];function _d(a){var s='';for(var i=0;i<a.length;i++)s+=String.fromCharCode(a[i]-7);return s;}
  var touched=false,t0=Date.now();['keydown','pointerdown','touchstart'].forEach(function(e){document.addEventListener(e,function(){touched=true;},{passive:true,capture:true});});
  function say(f,k,t){var m=f.querySelector('.sc-msg');if(!m){m=document.createElement('div');m.className='sc-msg';m.setAttribute('role','status');f.appendChild(m);}m.textContent=t;m.style.cssText='margin-top:12px;padding:12px 14px;border-radius:8px;font-size:.95rem;'+(k==='ok'?'background:#ECFDF3;color:#054F31;border:1px solid #A6F4C5':k==='wait'?'background:#EFF8FF;color:#0B4A6F;border:1px solid #B2DDFF':'background:#FEF3F2;color:#7A271A;border:1px solid #FECDCA');}
  [].forEach.call(document.querySelectorAll('form[data-sc="lead"]'),function(f){f.addEventListener('submit',function(e){e.preventDefault();var hp=f.querySelector('[name="_honey"]');if(hp&&hp.value)return;if(!touched||Date.now()-t0<3500){say(f,'err','Take a moment to fill in the form, then press send again.');return;}if(!f.checkValidity()){f.reportValidity();return;}var b=f.querySelector('[type="submit"]');if(b)b.disabled=true;say(f,'wait','Sending...');var fd=new FormData(f);fd.append('page_url',location.href);fd.append('source_site','searchconverts.com');fd.append('_template','table');fd.append('_captcha','false');
    fetch('https://formsubmit.co/ajax/'+_d(_L),{method:'POST',headers:{'Accept':'application/json'},body:fd}).then(function(r){return r.json().then(function(j){return {ok:r.ok,j:j};},function(){return {ok:r.ok,j:null};});}).then(function(res){if(res.ok&&res.j&&String(res.j.success)==='true'){say(f,'ok','Got it. A real person replies within one business day. Faster: call 1-800-481-8638.');f.reset();}else{say(f,'err','We could not confirm delivery. Please call 1-800-481-8638.');if(b)b.disabled=false;}}).catch(function(){say(f,'err','The message did not send. Please call 1-800-481-8638.');if(b)b.disabled=false;});});});
  var p=document.getElementById('sxprog');if(p){function u(){var d=document.documentElement,s=d.scrollTop||document.body.scrollTop,h=d.scrollHeight-d.clientHeight;p.style.width=(h>0?Math.min(100,s/h*100):0)+'%';}window.addEventListener('scroll',u,{passive:true});u();}
})();
