/* Scout — the Search Converts guide. Injects its own markup. Rule-based; never claims to be a person. */
(function(){'use strict';
var D=document,W=window;if(W.__scout)return;W.__scout=1;
var RM=W.matchMedia&&W.matchMedia('(prefers-reduced-motion:reduce)').matches;
var TEL='720-712-8615',TELH='tel:+17207128615';
var CSS='#sc-plane{position:fixed;top:8vh;left:-320px;width:240px;z-index:9998;pointer-events:none;filter:drop-shadow(0 10px 18px rgba(0,0,0,.18))}#sc-plane.fly{animation:scfly 3.2s cubic-bezier(.3,.6,.4,1) forwards}@keyframes scfly{to{left:calc(100vw + 40px)}}'+
'#sc-stage{position:fixed;right:22px;bottom:0;width:200px;z-index:9999;transform:translateY(-120vh);pointer-events:none;transition:transform .5s}#sc-stage.drop{animation:scdrop 3.2s cubic-bezier(.45,.05,.55,.95) forwards}@keyframes scdrop{0%{transform:translateY(-120vh) rotate(-3deg)}70%{transform:translateY(-6vh) rotate(3deg)}85%{transform:translateY(0) rotate(0)}92%{transform:translateY(-14px)}100%{transform:translateY(0)}}#sc-stage.static{transform:none;animation:none}#sc-stage.gone{transform:translateX(150%)!important;animation:none}'+
'#sc-stage #chute{transition:opacity .5s,transform .8s;transform-origin:50% 100%}#sc-stage.landed #chute{opacity:0;transform:scale(.4) translateY(120px)}#sc-stage.landed .wave{animation:scwave 1.2s ease-in-out 3}@keyframes scwave{0%,100%{transform:rotate(0)}50%{transform:rotate(-38deg)}}.wave{transform-origin:14% 20%}'+
'#sc-bub{position:fixed;right:236px;bottom:110px;max-width:280px;background:#fff;border-radius:18px;padding:14px 16px;box-shadow:0 18px 44px rgba(16,24,40,.18);font:15px/1.5 Inter,system-ui,sans-serif;color:#101828;opacity:0;transform:translateY(10px);transition:opacity .5s,transform .5s;z-index:9999;pointer-events:none}#sc-bub.on{opacity:1;transform:none;pointer-events:auto}#sc-bub::after{content:"";position:absolute;right:-12px;top:30px;border:12px solid transparent;border-left-color:#fff;border-right:0}#sc-bub b{color:#e3111f}#sc-bub a{color:#2563eb;font-weight:700}'+
'#sc-x{position:fixed;right:18px;bottom:236px;width:36px;height:36px;border-radius:50%;background:#0b1220;color:#fff;border:0;font-size:19px;cursor:pointer;z-index:10001;display:none;box-shadow:0 6px 16px rgba(0,0,0,.25)}#sc-x.on{display:block}'+
'#sc-open{position:fixed;right:70px;bottom:236px;height:36px;padding:0 14px;border-radius:18px;background:#e3111f;color:#fff;border:0;font:800 12px/1 Inter,sans-serif;cursor:pointer;z-index:10001;display:none;box-shadow:0 6px 16px rgba(227,17,31,.35)}#sc-open.on{display:block}'+
'#sc-tab{position:fixed;right:0;top:46vh;width:72px;height:146px;background:linear-gradient(160deg,#e3111f,#b30d19);border-radius:22px 0 0 22px;box-shadow:-8px 12px 30px rgba(227,17,31,.35);cursor:pointer;display:none;z-index:9999;transition:transform .25s;border:0;padding:0}#sc-tab:hover{transform:translateX(-6px)}#sc-tab.on{display:block}#sc-tab svg{position:absolute;left:-44px;top:-38px;width:146px;transform:rotate(-14deg)}#sc-tab span{position:absolute;right:9px;bottom:12px;color:#fff;font:800 11px/1 Inter,sans-serif;letter-spacing:.14em;writing-mode:vertical-rl;transform:rotate(180deg)}.scpop{animation:scpop .5s cubic-bezier(.2,1.4,.4,1) 1}@keyframes scpop{from{transform:scale(.6) translateX(60px)}to{transform:none}}'+
'#sc-panel{position:fixed;right:18px;bottom:18px;width:380px;max-width:calc(100vw - 24px);height:600px;max-height:calc(100vh - 40px);background:#fff;border-radius:22px;box-shadow:0 40px 100px rgba(11,18,32,.35);z-index:10002;display:none;flex-direction:column;overflow:hidden;border:1px solid #e4e7ec}#sc-panel.on{display:flex}'+
'#sc-panel .hd{display:flex;align-items:center;gap:10px;padding:12px 14px;background:linear-gradient(120deg,#0b1220,#1d2939);color:#fff}#sc-panel .hd svg{width:44px;height:44px}#sc-panel .hd b{display:block;font:800 14px/1.2 Inter,sans-serif}#sc-panel .hd small{color:#c7cee0;font-size:12px}#sc-panel .hd button{margin-left:auto;background:rgba(255,255,255,.12);border:0;color:#fff;width:34px;height:34px;border-radius:50%;font-size:18px;cursor:pointer}'+
'#sc-log{flex:1;overflow-y:auto;padding:14px;display:flex;flex-direction:column;gap:10px;background:#f6f8fc}.scm{max-width:88%;padding:10px 13px;border-radius:16px;line-height:1.5;font:15px/1.5 Inter,sans-serif}.scm.b{background:#fff;border:1.5px solid #e4e7ec;border-bottom-left-radius:4px;align-self:flex-start;color:#101828}.scm.u{background:#e3111f;color:#fff;border-bottom-right-radius:4px;align-self:flex-end}.scm a{color:#2563eb;font-weight:700}.scm b{color:#b30d19}.scm.u b{color:#fff}'+
'#sc-qs{display:flex;flex-wrap:wrap;gap:6px;padding:0 14px 10px;background:#f6f8fc}#sc-qs button{background:#fff;border:1.5px solid #e4e7ec;border-radius:20px;padding:7px 11px;font:600 12.5px Inter,sans-serif;cursor:pointer;color:#101828}#sc-qs button:hover{border-color:#e3111f;color:#e3111f}'+
'#sc-form{display:flex;gap:8px;padding:12px;border-top:1.5px solid #e4e7ec;background:#fff}#sc-form input{flex:1;padding:12px 14px;border:2px solid #e4e7ec;border-radius:12px;font:16px Inter,sans-serif;min-height:46px}#sc-form button{background:#e3111f;color:#fff;border:0;border-radius:12px;padding:0 16px;font:800 13px Inter,sans-serif;cursor:pointer}'+
'@media(max-width:600px){#sc-stage{width:150px;right:8px}#sc-bub{right:166px;max-width:180px;font-size:13px;bottom:80px}#sc-x{bottom:196px;right:6px}#sc-open{bottom:196px;right:50px}#sc-panel{right:8px;bottom:8px;height:78vh}}'+
'@media(prefers-reduced-motion:reduce){#sc-plane.fly,#sc-stage.drop,.wave,.scpop{animation:none!important}}';
var SVG='<svg viewBox="0 0 230 300" width="200" height="300" aria-hidden="true"><defs><radialGradient id="sclens" cx="42%" cy="36%" r="60%"><stop offset="0" stop-color="#fff" stop-opacity=".95"/><stop offset=".18" stop-color="#dff4ff" stop-opacity=".85"/><stop offset=".55" stop-color="#8fd3ff" stop-opacity=".55"/><stop offset=".85" stop-color="#2b7fd6" stop-opacity=".55"/><stop offset="1" stop-color="#0b3f8a" stop-opacity=".7"/></radialGradient><radialGradient id="scglow" cx="50%" cy="50%" r="50%"><stop offset=".6" stop-color="#fff" stop-opacity="0"/><stop offset="1" stop-color="#fff" stop-opacity=".55"/></radialGradient><linearGradient id="scrim" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#fdfdfd"/><stop offset=".25" stop-color="#9aa6b8"/><stop offset=".5" stop-color="#e9edf3"/><stop offset=".75" stop-color="#6b7688"/><stop offset="1" stop-color="#d7dce6"/></linearGradient><linearGradient id="scwood" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#7a4a1f"/><stop offset=".4" stop-color="#c98b4b"/><stop offset=".6" stop-color="#a86a30"/><stop offset="1" stop-color="#5e3616"/></linearGradient><linearGradient id="scshirt" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#1c4fd6"/><stop offset=".5" stop-color="#3b7cff"/><stop offset="1" stop-color="#1a3fa8"/></linearGradient><linearGradient id="scred" x1="0" y1="1" x2="1" y2="0"><stop offset="0" stop-color="#b30d19"/><stop offset="1" stop-color="#ff3b47"/></linearGradient><linearGradient id="scsilk" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#ff5f6d"/><stop offset=".5" stop-color="#fff"/><stop offset="1" stop-color="#3b7cff"/></linearGradient><filter id="scsoft"><feGaussianBlur stdDeviation="1.2"/></filter><filter id="scsh" x="-30%" y="-30%" width="160%" height="160%"><feDropShadow dx="0" dy="10" stdDeviation="8" flood-color="#0b1220" flood-opacity=".28"/></filter></defs>'+
'<g id="chute"><path d="M20 70 Q115 -30 210 70 L115 76 Z" fill="url(#scsilk)" stroke="#c9d6e8" stroke-width="2"/><path d="M20 70 Q68 20 115 76 M115 76 Q162 20 210 70" fill="none" stroke="#fff" stroke-opacity=".6" stroke-width="2"/><path d="M26 72 L88 150 M62 76 L96 150 M168 76 L134 150 M204 72 L142 150" stroke="#556" stroke-width="1.6"/></g>'+
'<ellipse cx="118" cy="288" rx="70" ry="9" fill="#0b1220" opacity=".18"/><g filter="url(#scsh)"><path d="M98 172 L136 172 L142 290 L92 290 Z" fill="url(#scwood)"/><rect x="94" y="168" width="46" height="18" rx="6" fill="url(#scrim)"/><path d="M96 190 L138 190 L141 252 L93 252 Z" fill="url(#scshirt)"/><path d="M102 240 L112 226 L120 234 L134 214" fill="none" stroke="url(#scred)" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><path d="M126 210 L138 210 L138 222 Z" fill="#ff3b47"/><path d="M96 200 Q74 214 70 236" fill="none" stroke="#f5cba7" stroke-width="11" stroke-linecap="round"/><g class="wave"><path d="M138 200 Q160 190 176 168" fill="none" stroke="#f5cba7" stroke-width="11" stroke-linecap="round"/><circle cx="178" cy="165" r="9" fill="#f5cba7"/></g><circle cx="70" cy="238" r="9" fill="#f5cba7"/><rect x="98" y="262" width="14" height="24" rx="5" fill="#2f3450"/><rect x="122" y="262" width="14" height="24" rx="5" fill="#2f3450"/><ellipse cx="103" cy="288" rx="14" ry="6" fill="#e3111f"/><ellipse cx="131" cy="288" rx="14" ry="6" fill="#e3111f"/></g>'+
'<g filter="url(#scsh)"><circle cx="117" cy="104" r="70" fill="url(#scrim)"/><circle cx="117" cy="104" r="60" fill="#0b3f8a"/><circle cx="117" cy="104" r="60" fill="url(#sclens)"/><path d="M64 120 Q117 150 170 112" fill="none" stroke="#fff" stroke-opacity=".35" stroke-width="6" filter="url(#scsoft)"/><ellipse cx="90" cy="70" rx="22" ry="12" fill="#fff" opacity=".8" transform="rotate(-30 90 70)" filter="url(#scsoft)"/><circle cx="150" cy="130" r="9" fill="#fff" opacity=".5" filter="url(#scsoft)"/><circle cx="117" cy="104" r="60" fill="url(#scglow)"/>'+
'<circle cx="97" cy="104" r="15" fill="none" stroke="#0b1220" stroke-width="3.5"/><circle cx="137" cy="104" r="15" fill="none" stroke="#0b1220" stroke-width="3.5"/><path d="M112 104 L122 104" stroke="#0b1220" stroke-width="3.5"/><path d="M82 100 L70 92 M152 100 L164 92" stroke="#0b1220" stroke-width="3.5" stroke-linecap="round"/><circle cx="97" cy="104" r="14" fill="#fff" opacity=".55"/><circle cx="137" cy="104" r="14" fill="#fff" opacity=".55"/><circle cx="99" cy="106" r="6" fill="#0b1220"/><circle cx="139" cy="106" r="6" fill="#0b1220"/><circle cx="101" cy="103" r="2" fill="#fff"/><circle cx="141" cy="103" r="2" fill="#fff"/><path d="M86 86 Q97 80 108 86" fill="none" stroke="#0b1220" stroke-width="3" stroke-linecap="round"/><path d="M126 86 Q137 79 148 85" fill="none" stroke="#0b1220" stroke-width="3" stroke-linecap="round"/><path d="M100 128 Q117 142 134 128" fill="none" stroke="#0b1220" stroke-width="3.5" stroke-linecap="round"/><ellipse cx="86" cy="122" rx="7" ry="4" fill="#ff7a8a" opacity=".55"/><ellipse cx="148" cy="122" rx="7" ry="4" fill="#ff7a8a" opacity=".55"/><path d="M62 78 A70 70 0 0 1 128 36" fill="none" stroke="#fff" stroke-opacity=".9" stroke-width="5" stroke-linecap="round"/></g></svg>';
var HEAD='<svg viewBox="0 0 230 180" aria-hidden="true"><defs><radialGradient id="sclens2" cx="42%" cy="36%" r="60%"><stop offset="0" stop-color="#fff" stop-opacity=".95"/><stop offset=".55" stop-color="#8fd3ff" stop-opacity=".6"/><stop offset="1" stop-color="#0b3f8a" stop-opacity=".7"/></radialGradient><linearGradient id="scrim2" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#fdfdfd"/><stop offset=".5" stop-color="#8f9bb0"/><stop offset="1" stop-color="#d7dce6"/></linearGradient></defs><circle cx="117" cy="104" r="70" fill="url(#scrim2)"/><circle cx="117" cy="104" r="60" fill="#0b3f8a"/><circle cx="117" cy="104" r="60" fill="url(#sclens2)"/><ellipse cx="90" cy="70" rx="22" ry="12" fill="#fff" opacity=".8" transform="rotate(-30 90 70)"/><circle cx="97" cy="104" r="15" fill="none" stroke="#0b1220" stroke-width="3.5"/><circle cx="137" cy="104" r="15" fill="none" stroke="#0b1220" stroke-width="3.5"/><path d="M112 104 L122 104" stroke="#0b1220" stroke-width="3.5"/><circle cx="99" cy="106" r="6" fill="#0b1220"/><circle cx="139" cy="106" r="6" fill="#0b1220"/><circle cx="101" cy="103" r="2" fill="#fff"/><circle cx="141" cy="103" r="2" fill="#fff"/><path d="M100 128 Q117 142 134 128" fill="none" stroke="#0b1220" stroke-width="3.5" stroke-linecap="round"/><path d="M62 78 A70 70 0 0 1 128 36" fill="none" stroke="#fff" stroke-opacity=".9" stroke-width="5" stroke-linecap="round"/></svg>';
var PLANE='<svg viewBox="0 0 260 90" aria-hidden="true"><defs><linearGradient id="scpl" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#c9d6e8"/></linearGradient></defs><path d="M10 48 L150 40 L232 34 Q252 34 246 46 L236 56 L150 62 L40 66 Q18 66 10 48Z" fill="url(#scpl)" stroke="#8fa4c4" stroke-width="2"/><path d="M96 42 L120 12 L150 12 L128 44Z" fill="#e3111f"/><path d="M110 60 L128 82 L150 82 L132 60Z" fill="#e3111f"/><path d="M226 36 L238 14 L252 14 L244 36Z" fill="#e3111f"/><circle cx="60" cy="52" r="5" fill="#0b1220"/><circle cx="80" cy="51" r="5" fill="#0b1220"/><circle cx="100" cy="50" r="5" fill="#0b1220"/><text x="150" y="53" font-size="11" font-weight="800" fill="#0b1220" font-family="Inter,sans-serif">SEARCH CONVERTS</text></svg>';

/* ---------- openers by page, never repeated in a session ---------- */
var OPEN={
 '/':["Hi, I'm Scout. Quick one: if your site got ten more calls a week, what would that be worth? No promises — but with the right strategy it's very possible.","Hey. Fun fact: most business websites convert under 3% of visitors. The other 97% walk out the locked door. Want to see where yours leaks?","What's up? I'm the guide here. Ask me anything — CRO, ads, the tools, or 'how do I install this on my site.'"],
 '/conversion-optimization/':["Reading about conversion? Good. The short version: the site has to answer 'what happens next' before anyone calls. Ask me how.","Here's one that gets people thinking: a 1% lift in conversion on 5,000 visits is 50 extra customers a month. What's one worth to you?"],
 '/our-work/':["This is the real work — every card links to a live site. Notice how each one puts the phone in the first screen? That's not an accident.","Want the honest version of how one of these was built? Ask me about any of them."],
 '/pitch/':["Nine slides. Ends with a yes or a not-yet. I'll be here if a slide raises a question.","Tip: slide 6 is the one people screenshot. It's the cost of waiting."],
 'default':["Hey — I'm Scout, the guide. Ask me about this page, the tools, pricing, or how to get started.","Hi. If this page doesn't answer your question, I probably can. Try 'what does this cost' or 'call me.'","What's up? Quick gut-check: is your site making people call, or talking them out of it? I can help you tell."]};
/* ---------- knowledge base ---------- */
var KB=[
 [['hi','hello','hey','yo','sup','what\'s up','whats up','howdy','hola','good morning','good afternoon','good evening','how are you','how\'s it going','hows it going'],["Hey! Doing great — thanks for asking. I'm Scout, Search Converts' guide. Ask me about conversion, ads, the free tools, prices, or say <b>call me</b> and I'll set that up.","What's up! I'm Scout. I know this site, the free tools, Eye To Ad Media's search side, and a little sales psychology. Where do you want to start?","Yo. Good to see you. Quick question for you: is your website making people call, or quietly talking them out of it? I can help you find out."]],
 [['who are you','what are you','are you a bot','are you ai','are you real','are you human','robot'],["I'm Scout — a scripted guide, not a person and not a large language model. I match what you type to what I know, so I never make things up. For anything I can't answer, a real person will: <a href=\""+TELH+"\">"+TEL+"</a>."]],
 [['call me','call now','can you call','when can you call','phone call','give me a call','ring me','contact me','reach out'],["Absolutely. Two ways: call us now at <a href=\""+TELH+"\">"+TEL+"</a>, or <a href=\"/contact/\">leave your number here</a> and a real person — not me — calls back within one business day, usually faster. What time of day is best for you?"]],
 [['price','cost','how much','pricing','rates','budget','expensive','cheap','afford'],["Honest answer: every engagement is quoted to the business, after one conversation about what you sell and what a customer is worth. Most campaigns run $500–$3,000 a month. Websites range from simple builds quoted per project to $99/month subscribe-to-own custom sites. No contract is sent until you're ready. Want the range for your situation? <a href=\"/contact/\">Tell us the business</a> or call <a href=\""+TELH+"\">"+TEL+"</a>."]],
 [['install','embed','put this on my site','add this to my site','how do i put','how does the generator','generator code','embed code','copy the code','html code','snippet','plugin','wordpress install','add to wordpress','add to shopify'],["Good question — the tools on this site run in your browser and the outputs (schema, scripts, copy) are yours to use. Installing on your own site means pasting the code into your page's HTML, or a code block in WordPress/Shopify/Webflow. If that sentence made you tired: <b>we install it for free for clients</b>, and we'll build a custom version. <a href=\"/contact/\">Say which tool</a> or call <a href=\""+TELH+"\">"+TEL+"</a>."]],
 [['conversion','cro','convert','conversion rate','why is my conversion','not converting','no calls','no leads','traffic but'],["Conversion is the share of visitors who do the thing — call, book, buy. Most sites sit under 3%. The usual leaks: the headline names the company instead of the customer's problem, the phone number is below the fold, there are five actions instead of one, and nothing answers 'what happens next.' We find yours in a <a href=\"/cro-audit/\">conversion audit</a>. What's your site's main action — a call, a form, a purchase?"]],
 [['audit','free audit','check my site','review my site','look at my site','analyze','analyse'],["The <a href=\"/cro-audit/\">conversion audit</a> is free: we look at your site the way a stranger does — first screen, offer, proof, the path to a call — and hand you the leaks, ranked. You keep it whether or not you hire us. <a href=\"/contact/\">Send the URL</a>."]],
 [['seo','rank','ranking','google','search','denver seo','found on google','page one','maps','local seo'],["Search — being found — is the other half of the equation, and it's handled by our sister brand <a href=\"https://eyetoad.com/\" rel=\"noopener\">Eye To Ad Media</a>: Denver SEO, Google Maps, and being cited by AI answers. This site is the conversion half: what happens after they find you. Most businesses need both, in that order. Which one is broken for you right now?"]],
 [['ai','chatgpt','ai search','ai overviews','cited','citation','perplexity','gemini'],["AI answers (ChatGPT, Google's AI, Perplexity) now recommend businesses directly. They cite the ones whose facts agree everywhere and whose pages answer questions plainly. Eye To Ad Media builds that layer — <a href=\"https://eyetoad.com/ai-marketing-agency/\" rel=\"noopener\">AI marketing</a> — and this site makes sure the click converts. Can you picture leading the AI citations in your industry? It's more possible than most people think."]],
 [['ads','google ads','ppc','facebook ads','meta','paid','adwords','retargeting','programmatic','ctv','radio','tv','direct mail'],["We run paid media to profit, not to spend: <a href=\"/google-ads-management/\">Google Ads</a>, <a href=\"/facebook-ads-management/\">Meta</a>, <a href=\"/programmatic-advertising/\">programmatic</a>, <a href=\"/ctv-advertising/\">CTV</a>, <a href=\"/retargeting/\">retargeting</a>, even <a href=\"/radio-tv-advertising/\">radio and TV</a>. One rule: we fix the landing page before we buy the traffic, because ads into a leaky page just make the leak more expensive. What are you running now?"]],
 [['website','web design','new site','redesign','rebuild','wordpress','shopify','webflow','wix','squarespace','hand coded','custom coded'],["We build on whatever fits: hand-coded when speed and conversion matter most, <a href=\"/shopify-web-designer/\">Shopify</a> for stores, <a href=\"/wordpress-web-designer/\">WordPress</a>, <a href=\"/webflow-web-designer/\">Webflow</a>, and we'll rescue a <a href=\"/wix-web-designer/\">Wix</a> or <a href=\"/squarespace-web-designer/\">Squarespace</a> site. Custom-coded sites start at $99/month subscribe-to-own. The company-side quotes live at <a href=\"https://denver-webdesign.com/\" rel=\"noopener\">Denver Web Design</a>. What's the site's job — calls, sales, or credibility?"]],
 [['tool','tools','calculator','free tool','generator'],["The free tools: the <a href=\"/conversion-calculator/\">conversion rate calculator</a>, <a href=\"/form-friction-calculator/\">form friction</a>, <a href=\"/ab-test-simulator/\">A/B significance</a>, <a href=\"/marketing-budget-calculator/\">budget calculator</a>, <a href=\"/marketing-plan-builder/\">plan builder</a>, plus the ones on <a href=\"/cro-audit/\">the audit</a> and <a href=\"/website-conversion-rate/\">conversion gauge</a> pages. Technical SEO tools are at <a href=\"https://eyetoad.com/free-seo-tools/\" rel=\"noopener\">Eye To Ad Media</a>. Which problem are you trying to size?"]],
 [['our work','examples','portfolio','case study','case studies','who have you worked with','clients'],["All of it is live and clickable on <a href=\"/our-work/\">our work</a> — a metro-Atlanta roofing company, a clinician-led clinic, a walk-in 3D mall, and more. And our own companies run on the same methods; one holds three listings on a single Google page for its core terms. Want the honest story behind any of them?"]],
 [['sales','close','closing','objection','tie down','tie-down','trial close','price conditioning','spin','spin selling','sales training'],["Sales is where a lead becomes revenue, and it's our founder's background — sales manager for multi-million-dollar companies before the agency. Quick lesson: a <b>tie-down</b> is a small agreement question ('…isn't it?'); a <b>trial close</b> asks for an opinion, not a decision ('how would that change things for you?'); <b>price conditioning</b> means they hear the range before the number. SPIN: Situation, Problem, Implication, Need-payoff — ask about the cost of the problem before you ever pitch. <a href=\"/sales-training/\">Sales training</a> is one-on-one or team, quoted after a conversation. What's the objection you hear most?"]],
 [['lead','leads','lead generation','more customers','more clients','more calls','grow','growth'],["Here's one to sit with: what would an extra 30 clients a week do for your business? No promises — but with the right strategy it's possible, and we've watched it happen. Leads come from three places: being found (search, Maps, AI), being chosen (the site converts), and being followed up in the first hour. <a href=\"/lead-generation/\">Lead generation</a> covers all three. Which one is your bottleneck?"]],
 [['social','facebook','instagram','groups','facebook groups','social media'],["<a href=\"/social-media-marketing/\">Social media marketing</a> here means Meta ads with pixel and conversion setup, posting on your behalf, and something unusual: reach in private local buy/sell/trade groups through <a href=\"https://socialmybusiness.com/\" rel=\"noopener\">Social My Business</a>. Where do your customers actually hang out?"]],
 [['press release','pr','press','news','directory','listing','citations'],["Two properties we own help with authority: <a href=\"https://pressreleaseforbusiness.com/\" rel=\"noopener\">Press Release For Business</a> publishes releases AI systems can quote, <a href=\"https://distributepressreleases.com/\" rel=\"noopener\">Distribute Press Releases</a> pushes them out, and <a href=\"https://usabusinesssearch.com/\" rel=\"noopener\">the directory</a> gives you a verified listing. Clients get put through them as part of a campaign."]],
 [['hours','open','when are you open','location','where are you','address','office'],["We're in Denver, Colorado and work with businesses nationally by phone. Reach us at <a href=\""+TELH+"\">"+TEL+"</a> or <a href=\"/contact/\">the contact page</a> — a real person replies within one business day."]],
 [['email','e-mail','mail'],["Email works: <a href=\"#\" data-email=\"text\">hello at searchconverts dot com</a> — or the <a href=\"/contact/\">form</a>, which lands in the same inbox with your page and tool already noted. Phone is fastest: <a href=\""+TELH+"\">"+TEL+"</a>."]],
 [['thanks','thank you','thx','cheers','appreciate'],["Anytime. If you want a human to take it from here: <a href=\""+TELH+"\">"+TEL+"</a>. Otherwise I'm on every page."]],
 [['bye','goodbye','see ya','later','no thanks','not interested'],["Fair enough — no pitch. I'll be in the tab on the right if you change your mind. Have a good one."]],
 [['color','colour','psychology','why red','button color'],["Color does three jobs: gets attention, tells the eye where to look, and makes one action obvious. Red gets attention; blue is trusted; the rule is one high-contrast button per screen. The details, with the honest science, are on <a href=\"/marketing-psychology/\">marketing psychology</a>. Try the live button test there."]],
 [['bubbles','game','interactive','fun','pop'],["Go pop the bubbles on <a href=\"/interactive-marketing/\">interactive marketing</a> — each one is a real stat, and it makes a point: attention is the first sale. We build playable things for businesses too."]],
 [['speed','slow','lighthouse','page speed','core web vitals','fast'],["Speed is a conversion lever: slower pages lose calls before anyone reads a word. Test yours free at <a href=\"https://pagespeed.web.dev/\" rel=\"noopener\">PageSpeed Insights</a> (that's Google's Lighthouse). If you're under 90 on mobile, that's fixable — and it's usually images and blocking scripts."]],
 [['guarantee','guaranteed','promise','results'],["No guarantees — nobody honest can promise rankings or a conversion rate, and Google's own guidance says so. What we promise is the work, the honesty, and to treat your business like our own. We test everything on our own companies first."]],
 [['start','get started','sign up','how do we start','next step','ready'],["Great — it all starts with strategy, and then actually starting. Step one is a 30-minute conversation: what you sell, what a customer is worth, where the leads come from now. Call <a href=\""+TELH+"\">"+TEL+"</a> or <a href=\"/free-strategy-session/\">book the strategy session</a>. No contract until you're ready."]],
 [['denverseo','denver seo .io','programming','coding','developer'],["The programming and coding side of search — the technical build — lives at <a href=\"https://denverseo.io/\" rel=\"noopener\">denverseo.io</a>; the agency side is <a href=\"https://eyetoad.com/\" rel=\"noopener\">Eye To Ad Media</a>. Same team, different lanes."]],
 [['affordable','cheap seo','low cost','small budget'],["Smaller budgets are real budgets. <a href=\"https://affordabledenverseo.com/\" rel=\"noopener\">Affordable Denver SEO</a> is built for exactly that — focused, honest, and quoted to what you can actually spend. And a $100 entry point exists at Eye To Ad Media for one focused deliverable."]]
];
var FALLBACK=["I don't have that one — I'm scripted, not an AI, so I won't guess. Try: <b>price</b>, <b>audit</b>, <b>call me</b>, <b>install this</b>, <b>our work</b>, or <b>how to start</b>. Or a human: <a href=\""+TELH+"\">"+TEL+"</a>.","That's outside what I know. What I can do: explain any service here, size a problem with the tools, or get a real person to call you — say <b>call me</b>."];
var CHIPS=['What does it cost?','Free audit','Call me','How do I install this?','Our work','How do we start?'];

/* ---------- build ---------- */
function build(){
  var st=D.createElement('style');st.textContent=CSS;D.head.appendChild(st);
  var pl=D.createElement('div');pl.id='sc-plane';pl.innerHTML=PLANE;D.body.appendChild(pl);
  var stage=D.createElement('div');stage.id='sc-stage';stage.setAttribute('aria-hidden','true');stage.innerHTML=SVG;D.body.appendChild(stage);
  var bub=D.createElement('div');bub.id='sc-bub';bub.setAttribute('role','status');D.body.appendChild(bub);
  var x=D.createElement('button');x.id='sc-x';x.type='button';x.setAttribute('aria-label','Close Scout');x.textContent='×';D.body.appendChild(x);
  var op=D.createElement('button');op.id='sc-open';op.type='button';op.textContent='Chat with Scout';D.body.appendChild(op);
  var tab=D.createElement('button');tab.id='sc-tab';tab.type='button';tab.setAttribute('aria-label','Open Scout');tab.innerHTML=HEAD+'<span>ASK SCOUT</span>';D.body.appendChild(tab);
  var panel=D.createElement('div');panel.id='sc-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Scout chat');panel.innerHTML='<div class="hd">'+HEAD+'<div><b>Scout</b><small>Search Converts guide · scripted, not a person</small></div><button type="button" id="sc-pclose" aria-label="Close chat">×</button></div><div id="sc-log" aria-live="polite"></div><div id="sc-qs">'+CHIPS.map(function(c){return '<button type="button" data-q="'+c+'">'+c+'</button>';}).join('')+'</div><form id="sc-form" autocomplete="off"><input id="sc-in" type="text" placeholder="Ask Scout anything…" aria-label="Ask Scout" maxlength="300"><button type="submit">Ask</button></form>';D.body.appendChild(panel);
  return {pl:pl,stage:stage,bub:bub,x:x,op:op,tab:tab,panel:panel};
}
var el,said={},log,closed=false;
try{said=JSON.parse(sessionStorage.getItem('scSaid')||'{}');}catch(e){}
function pick(list){var k=list.filter(function(s){return !said[s.slice(0,30)];});if(!k.length){k=list;}var s=k[Math.floor(Math.random()*k.length)];said[s.slice(0,30)]=1;try{sessionStorage.setItem('scSaid',JSON.stringify(said));}catch(e){}return s;}
function opener(){var p=location.pathname;var list=OPEN[p]||OPEN['default'];return pick(list.concat(OPEN['default']).filter(function(v,i,a){return a.indexOf(v)===i;}));}
function say(html,who){var d=D.createElement('div');d.className='scm '+who;d.innerHTML=html;log.appendChild(d);log.scrollTop=log.scrollHeight;var m=d.querySelector('[data-email]');if(m&&W.SC){var E=[111,108,115,115,118,71,122,108,104,121,106,111,106,118,117,125,108,121,123,122,53,106,118,116],s='';for(var i=0;i<E.length;i++)s+=String.fromCharCode(E[i]-7);m.setAttribute('href','mail'+'to:'+s);m.textContent=s;}}
function answer(q){var t=q.toLowerCase().replace(/[^a-z0-9@'\s.-]/g,' ');say(W.SC?W.SC.esc(q):q,'u');var best=null,bs=0;KB.forEach(function(k){var s=0;k[0].forEach(function(w){if(t.indexOf(w)>-1)s+=w.length+(t===w?10:0);});if(s>bs){bs=s;best=k;}});
  setTimeout(function(){say(best?pick(best[1]):pick(FALLBACK),'b');},380);}
function openPanel(){el.panel.classList.add('on');el.bub.classList.remove('on');el.x.classList.remove('on');el.op.classList.remove('on');el.stage.classList.add('gone');el.tab.classList.remove('on');if(!log.children.length)say(opener(),'b');setTimeout(function(){try{D.getElementById('sc-in').focus();}catch(e){}},200);try{sessionStorage.setItem('scOpen','1');}catch(e){}}
function closePanel(){el.panel.classList.remove('on');toTab();try{sessionStorage.setItem('scOpen','0');}catch(e){}}
function toTab(){closed=true;el.bub.classList.remove('on');el.x.classList.remove('on');el.op.classList.remove('on');el.stage.classList.add('gone');setTimeout(function(){el.tab.classList.add('on','scpop');},420);try{sessionStorage.setItem('scClosed','1');}catch(e){}}
function land(){el.stage.classList.add('landed');setTimeout(function(){if(closed)return;el.bub.innerHTML=opener();el.bub.classList.add('on');el.x.classList.add('on');el.op.classList.add('on');},500);}
function arrive(){if(RM){el.stage.classList.add('static','landed');land();return;}el.pl.classList.add('fly');setTimeout(function(){el.stage.classList.add('drop');},900);setTimeout(land,4100);}
function boot(){el=build();log=D.getElementById('sc-log');
  el.x.addEventListener('click',toTab);el.tab.addEventListener('click',function(){el.tab.classList.remove('on');closed=false;openPanel();});el.op.addEventListener('click',openPanel);D.getElementById('sc-pclose').addEventListener('click',closePanel);
  D.getElementById('sc-form').addEventListener('submit',function(e){e.preventDefault();var v=D.getElementById('sc-in').value.trim();if(!v)return;D.getElementById('sc-in').value='';answer(v);});
  D.getElementById('sc-qs').addEventListener('click',function(e){var b=e.target.closest('[data-q]');if(b)answer(b.getAttribute('data-q'));});
  el.bub.addEventListener('click',openPanel);
  var seen=false,wasOpen=false,wasClosed=false;try{seen=sessionStorage.getItem('scSeen')==='1';wasOpen=sessionStorage.getItem('scOpen')==='1';wasClosed=sessionStorage.getItem('scClosed')==='1';}catch(e){}
  if(wasOpen){el.stage.classList.add('gone');openPanel();return;}
  if(seen||wasClosed||D.body.getAttribute('data-scout')==='tab'){el.stage.classList.add('gone');el.tab.classList.add('on');closed=true;return;}
  try{sessionStorage.setItem('scSeen','1');}catch(e){}
  var fired=false;function go(){if(fired)return;fired=true;W.removeEventListener('scroll',onS);setTimeout(arrive,300);}function onS(){if(W.pageYOffset>200)go();}
  W.addEventListener('scroll',onS,{passive:true});setTimeout(go,7000);
}
if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',boot);else boot();
})();
